export const statusDict = {
  en: {
    'status.title': 'Activity and AI',
    'status.open': 'Show activity and AI status',
    'status.chat': 'Chat',
    'status.search': 'Document search',
    'status.refinement': 'Search refinement',
    'status.optional': 'Optional',
    'status.translation': 'Translation',
    'status.transcription': 'Audio transcription',
    'status.ready': 'Ready',
    'status.remote': 'External provider',
    'status.standby': 'On demand',
    'status.unloaded': 'Not loaded',
    'status.loading': 'Preparing',
    'status.working': 'Working',
    'status.failed': 'Needs attention',
    'status.off': 'Off',
    'status.skipped': 'Skipped',
    'status.missing': 'Model missing',
    'status.checking': 'Checking',
    'status.unknown': 'Status unavailable',
    'status.idle': 'AI status',
    'status.chatReady': 'Chat ready',
    'status.chatRemote': 'Chat via external provider',
    'status.chatStandby': 'Chat available on demand',
    'status.chatUnloaded': 'Chat not loaded',
    'status.attention': 'AI needs attention',
    'status.prepareChat': 'Preparing chat',
    'status.prepareSearch': 'Preparing document search',
    'status.prepareRefinement': 'Preparing search refinement',
    'status.indexing': 'Indexing documents',
    'status.restoring': 'Returning to chat',
    'status.updatingSearch': 'Updating document search',
    'status.searchProgress': '{done} of {total} passages',
    'status.running': 'In progress',
    'status.waiting': 'Waiting',
    'status.moreJobs': '+{count} waiting',
    'status.job.chat': 'Generating an answer',
    'status.job.quiz': 'Creating a quiz',
    'status.job.summary': 'Summarizing a document',
    'status.job.writing': 'Drafting text',
    'status.job.translation': 'Translating text',
    'status.job.transcription': 'Transcribing audio',
    'status.jobHint':
      'Chat, writing and translation share one queue. Stop a generation in its tool.',
    'status.queueBehindIndex': 'AI requests wait while documents are indexed.',
    'status.chatReadyHint': 'Chat is ready to use with GPU acceleration.',
    'status.chatWaitingHint': 'Chat resumes when the current GPU task finishes.',
    'status.remoteHint':
      'Uses your selected external provider. Its connection is checked when you make a request.',
    'status.standbyHint': 'Available when needed. GPU memory is free for the current task.',
    'status.unloadedHint':
      'The model is not loaded. Check its setup in System if it does not start.',
    'status.loadingHint': 'Preparing the model on your selected GPU.',
    'status.checkingHint': 'Checking model availability.',
    'status.searchWorkingHint': 'Preparing your documents for search.',
    'status.failedHint': 'Open System to check the GPU and model setup.',
    'status.searchReadyHint': 'The document search model is loaded.',
    'status.refinementHint': 'Checks the relevance of search results before answering.',
    'status.refinementOff': 'Turned off in settings. Hybrid document search is still available.',
    'status.refinementSkipped':
      'Auto skips this extra model on a small GPU. Hybrid document search is still available.',
    'status.refinementUnknown':
      'GPU capacity could not be verified. Hybrid document search can continue without this step.',
    'status.translationHint': 'Uses the same model and queue as chat.',
    'status.audioStandby': 'The audio model is installed and loads when you start a transcription.',
    'status.audioWorking': 'Transcribing audio. Progress and Stop are available in Transcription.',
    'status.audioDownloading': 'Downloading the audio model.',
    'status.audioMissing':
      'No audio model is installed. Run model setup again to add transcription.',
    'status.stopIndexing': 'Stop indexing',
    'status.stopping': 'Stopping after this batch',
    'status.stopFailed': 'Indexing could not be stopped. Try again.',
    'status.system': 'Open System settings',
    'status.diagnostics': 'Technical details',
    'status.readFailed': 'Some status details could not be read. Open System to check the setup.',
    'status.close': 'Close status details',
    'status.issues': '{count} capabilities need attention',
  },
  de: {
    'status.title': 'Aktivität und KI',
    'status.open': 'Aktivität und KI-Status anzeigen',
    'status.chat': 'Chat',
    'status.search': 'Dokumentsuche',
    'status.refinement': 'Trefferprüfung',
    'status.optional': 'Optional',
    'status.translation': 'Übersetzung',
    'status.transcription': 'Transkription',
    'status.ready': 'Bereit',
    'status.remote': 'Externer Anbieter',
    'status.standby': 'Bei Bedarf',
    'status.unloaded': 'Nicht geladen',
    'status.loading': 'Wird vorbereitet',
    'status.working': 'In Arbeit',
    'status.failed': 'Aktion erforderlich',
    'status.off': 'Aus',
    'status.skipped': 'Übersprungen',
    'status.missing': 'Modell fehlt',
    'status.checking': 'Wird geprüft',
    'status.unknown': 'Status nicht verfügbar',
    'status.idle': 'KI-Status',
    'status.chatReady': 'Chat bereit',
    'status.chatRemote': 'Chat über externen Anbieter',
    'status.chatStandby': 'Chat bei Bedarf verfügbar',
    'status.chatUnloaded': 'Chat nicht geladen',
    'status.attention': 'KI benötigt Aufmerksamkeit',
    'status.prepareChat': 'Chat wird vorbereitet',
    'status.prepareSearch': 'Dokumentsuche wird vorbereitet',
    'status.prepareRefinement': 'Trefferprüfung wird vorbereitet',
    'status.indexing': 'Dokumente werden indexiert',
    'status.restoring': 'Zurück zum Chat',
    'status.updatingSearch': 'Dokumentsuche wird aktualisiert',
    'status.searchProgress': '{done} von {total} Abschnitten',
    'status.running': 'In Arbeit',
    'status.waiting': 'Wartet',
    'status.moreJobs': '+{count} warten',
    'status.job.chat': 'Antwort wird erstellt',
    'status.job.quiz': 'Quiz wird erstellt',
    'status.job.summary': 'Dokument wird zusammengefasst',
    'status.job.writing': 'Text wird entworfen',
    'status.job.translation': 'Text wird übersetzt',
    'status.job.transcription': 'Audio wird transkribiert',
    'status.jobHint':
      'Chat, Schreiben und Übersetzung teilen sich eine Warteschlange. Stoppe eine Erstellung im jeweiligen Werkzeug.',
    'status.queueBehindIndex': 'KI-Anfragen warten, während Dokumente indexiert werden.',
    'status.chatReadyHint': 'Der Chat ist mit GPU-Beschleunigung einsatzbereit.',
    'status.chatWaitingHint': 'Der Chat wird nach der aktuellen GPU-Aufgabe fortgesetzt.',
    'status.remoteHint':
      'Verwendet deinen gewählten externen Anbieter. Die Verbindung wird bei einer Anfrage geprüft.',
    'status.standbyHint':
      'Bei Bedarf verfügbar. Der GPU-Speicher ist für die aktuelle Aufgabe frei.',
    'status.unloadedHint':
      'Das Modell ist nicht geladen. Prüfe die Einrichtung unter System, falls es nicht startet.',
    'status.loadingHint': 'Das Modell wird auf deiner ausgewählten GPU vorbereitet.',
    'status.checkingHint': 'Die Modellverfügbarkeit wird geprüft.',
    'status.searchWorkingHint': 'Deine Dokumente werden für die Suche vorbereitet.',
    'status.failedHint': 'Prüfe GPU und Modelle in den Systemeinstellungen.',
    'status.searchReadyHint': 'Das Modell für die Dokumentsuche ist geladen.',
    'status.refinementHint': 'Prüft die Relevanz der Suchtreffer vor der Antwort.',
    'status.refinementOff':
      'In den Einstellungen ausgeschaltet. Die hybride Dokumentsuche bleibt verfügbar.',
    'status.refinementSkipped':
      'Auto überspringt dieses zusätzliche Modell bei wenig GPU-Speicher. Die hybride Dokumentsuche bleibt verfügbar.',
    'status.refinementUnknown':
      'Die GPU-Kapazität konnte nicht geprüft werden. Die hybride Dokumentsuche kann ohne diesen Schritt fortfahren.',
    'status.translationHint': 'Nutzt dasselbe Modell und dieselbe Warteschlange wie der Chat.',
    'status.audioStandby':
      'Das Audiomodell ist installiert und wird beim Start einer Transkription geladen.',
    'status.audioWorking':
      'Audio wird transkribiert. Fortschritt und Stopp findest du unter Transkription.',
    'status.audioDownloading': 'Das Audiomodell wird heruntergeladen.',
    'status.audioMissing':
      'Kein Audiomodell installiert. Führe die Modelleinrichtung erneut aus, um Transkription hinzuzufügen.',
    'status.stopIndexing': 'Indexierung stoppen',
    'status.stopping': 'Stopp nach diesem Durchlauf',
    'status.stopFailed': 'Die Indexierung konnte nicht gestoppt werden. Versuche es erneut.',
    'status.system': 'Systemeinstellungen öffnen',
    'status.diagnostics': 'Technische Details',
    'status.readFailed':
      'Einige Statusangaben konnten nicht gelesen werden. Prüfe die Einrichtung unter System.',
    'status.close': 'Statusdetails schließen',
    'status.issues': '{count} Funktionen benötigen Aufmerksamkeit',
  },
}
