// File-ROLE classification for codebase workspaces (ADR-0006). Refines the
// coarse code/doc/skip track (ignore.ts `fileTrack`) into the structural role a
// file plays — source vs test vs eval vs example vs config vs generated vs doc —
// so retrieval can prefer the IMPLEMENTATION over its tests/benchmarks for a
// "how does X work" question, and prefer tests when the user actually asks about
// tests.
//
// Pure + dependency-free + derived purely from the repo-relative PATH, so it can
// run at retrieval time off a chunk's stored heading_path[0] (no re-ingest) and
// is exactly consistent with isCodeHit, which routes on the same fileTrack.
//
// Path takes precedence over content: a `.ts` under `tests/` is a test even if it
// has a business-y name; a `.md` is doc wherever it lives.

import { fileTrack, type IndexTrack } from './ignore'

export type FileRole =
  | 'source' // application/library implementation — the default code target
  | 'test' // unit / integration / e2e / spec
  | 'eval' // quality evals + benchmarks
  | 'example' // fixtures, samples, demos, test helpers (support code / data)
  | 'config' // build/test/lint/deploy configuration
  | 'generated' // machine-emitted code (.d.ts, *.generated.*)
  | 'doc' // prose (markdown, rst, …) — the doc track
  | 'skip' // ignored / oversized / unindexed

function norm(relPath: string): string {
  return relPath.replace(/\\/g, '/').replace(/^\.?\//, '')
}
function basename(p: string): string {
  const s = norm(p)
  const i = s.lastIndexOf('/')
  return i === -1 ? s : s.slice(i + 1)
}

// --- path/filename predicates (forward-slashed relpath) -------------------

/** Any segment is a test dir, OR the filename carries a test marker. Covers JS/TS
 *  (.test/.spec, __tests__), Python (test_*, *_test, conftest), Go (*_test.go),
 *  JVM (*Test/*Tests/*Spec), Ruby (*_spec), and a bare top-level `test/` dir. */
function isTest(rel: string): boolean {
  const p = norm(rel)
  if (/(^|\/)(tests?|__tests__|spec|specs)\//i.test(p)) return true
  const name = basename(p).toLowerCase()
  return (
    /\.(test|spec)\.[cm]?[jt]sx?$/.test(name) ||
    /(^|[._-])test_[^/]*\.py$/.test(name) ||
    /_test\.(go|py|rb)$/.test(name) ||
    /_spec\.rb$/.test(name) ||
    /(test|tests|spec)\.(java|kt|kts|cs|scala)$/.test(name) ||
    name === 'conftest.py'
  )
}

/** Evals + benchmarks — quality/perf measurement, distinct from functional tests. */
function isEval(rel: string): boolean {
  return /(^|\/)(evals?|bench|benchmarks?|__benchmarks__)\//i.test(norm(rel))
}

/** Fixtures, examples, samples, demos, and test helper code — support, not impl.
 *  `helpers/` and `mocks/` are common in PRODUCTION trees (src/utils/helpers/),
 *  so they only count as support when nested under a test directory; `__mocks__`
 *  stays global (unambiguous Jest convention). Before the breadcrumb carried the
 *  full relative path these directory rules never matched — now that they do,
 *  the global variant would demote legitimate source by 0.5. */
function isExample(rel: string): boolean {
  const p = norm(rel)
  return (
    /(^|\/)(fixtures?|examples?|samples?|demos?|__mocks__|testdata)\//i.test(p) ||
    /(^|\/)(tests?|__tests__|spec|specs)\/(.*\/)?(helpers?|mocks?)\//i.test(p)
  )
}

/** Build/test/lint/deploy config. Most are JSON/YAML/TOML (code track) so they
 *  reach here; match by canonical filename + the `*.config.*` convention. */
function isConfig(rel: string): boolean {
  const name = basename(rel).toLowerCase()
  return (
    /^tsconfig(\..+)?\.json$/.test(name) ||
    /\.config\.[cm]?[jt]s$/.test(name) ||
    /^(vite|vitest|jest|playwright|rollup|webpack|babel|tailwind|postcss|astro|electron\.vite)\.config\.[cm]?[jt]s$/.test(
      name,
    ) ||
    /^\.?eslintrc(\..+)?$/.test(name) ||
    /^\.prettierrc/.test(name) ||
    name === 'package.json' ||
    name === 'pyproject.toml' ||
    name === 'cargo.toml' ||
    name === 'go.mod' ||
    name === 'makefile' ||
    name === 'tsconfig.json' ||
    /^\.env(\..+)?$/.test(name)
  )
}

/** Machine-generated code — never the answer to "how does X work". */
function isGenerated(rel: string): boolean {
  const name = basename(rel).toLowerCase()
  return (
    /\.d\.ts$/.test(name) ||
    /\.generated\.[^./]+$/.test(name) ||
    /(^|\/)gen(erated)?\//i.test(norm(rel))
  )
}

/**
 * Classify a file by its structural role. Consistent with `fileTrack`: a 'doc'
 * track file is role 'doc', 'skip' stays 'skip', and a 'code' file is refined
 * into source/test/eval/example/config/generated by path. Precedence (most
 * specific first): doc-by-extension → generated → test → eval → example →
 * config → source. `sizeBytes` is forwarded to fileTrack's oversize gate.
 */
export function fileRole(relPath: string, sizeBytes?: number, maxBytes?: number): FileRole {
  const track: IndexTrack = fileTrack(relPath, sizeBytes, maxBytes)
  if (track === 'skip') return 'skip'
  if (track === 'doc') return 'doc'
  // track === 'code' → refine by path/filename. Eval BEFORE test: code under
  // `tests/evals/` is eval, even though the path also contains `tests/`.
  if (isGenerated(relPath)) return 'generated'
  if (isEval(relPath)) return 'eval'
  if (isTest(relPath)) return 'test'
  if (isExample(relPath)) return 'example'
  if (isConfig(relPath)) return 'config'
  return 'source'
}

/** True for roles that are NOT the implementation — the ones a "how does X work"
 *  query should rank BELOW source. (example/config/generated are support code.) */
export function isSecondaryCodeRole(role: FileRole): boolean {
  return (
    role === 'test' ||
    role === 'eval' ||
    role === 'example' ||
    role === 'generated' ||
    role === 'config'
  )
}
